#!/bin/sh -ex

docker -v

if ! git merge-base --is-ancestor ${DRONE_COMMIT} HEAD; then
  echo "The commit ${DRONE_COMMIT} has not been found in HEAD."
  echo "Try to restart a build or open a new pull-request."
  exit 1
fi
